solution 'utilities'
    configurations {'release', 'debug'}
    location 'build'
    project 'cut'
        kind 'ConsoleApp'
        language 'C++'
        location 'build'
        files {'source/cut.cpp'}
        buildoptions {'-std=c++11'}
        linkoptions {'-std=c++11'}
        configuration 'release'
            targetdir 'build/release'
            defines {'NDEBUG'}
            flags {'OptimizeSpeed'}
        configuration 'debug'
            targetdir 'build/debug'
            defines {'DEBUG'}
            flags {'Symbols'}
        configuration 'linux'
            links {'pthread'}
    project 'rainmaker'
        kind 'ConsoleApp'
        language 'C++'
        location 'build'
        files {'source/html.hpp', 'third_party/lodepng/lodepng.cpp', 'source/rainmaker.cpp'}
        buildoptions {'-std=c++11'}
        linkoptions {'-std=c++11'}
        configuration 'release'
            targetdir 'build/release'
            defines {'NDEBUG'}
            flags {'OptimizeSpeed'}
        configuration 'debug'
            targetdir 'build/debug'
            defines {'DEBUG'}
            flags {'Symbols'}
        configuration 'linux'
            links {'pthread'}
    project 'es_to_csv'
        kind 'ConsoleApp'
        language 'C++'
        location 'build'
        files {'source/es_to_csv.cpp'}
        buildoptions {'-std=c++11'}
        linkoptions {'-std=c++11'}
        configuration 'release'
            targetdir 'build/release'
            defines {'NDEBUG'}
            flags {'OptimizeSpeed'}
        configuration 'debug'
            targetdir 'build/debug'
            defines {'DEBUG'}
            flags {'Symbols'}
        configuration 'linux'
            links {'pthread'}
    project 'dat_to_es'
        kind 'ConsoleApp'
        language 'C++'
        location 'build'
        files {'source/dat_to_es.cpp'}
        buildoptions {'-std=c++11'}
        linkoptions {'-std=c++11'}
        configuration 'release'
            targetdir 'build/release'
            defines {'NDEBUG'}
            flags {'OptimizeSpeed'}
        configuration 'debug'
            targetdir 'build/debug'
            defines {'DEBUG'}
            flags {'Symbols'}
        configuration 'linux'
            links {'pthread'}
    project 'statistics'
        kind 'ConsoleApp'
        language 'C++'
        location 'build'
        files {'source/statistics.cpp'}
        buildoptions {'-std=c++11'}
        linkoptions {'-std=c++11'}
        configuration 'release'
            targetdir 'build/release'
            defines {'NDEBUG'}
            flags {'OptimizeSpeed'}
        configuration 'debug'
            targetdir 'build/debug'
            defines {'DEBUG'}
            flags {'Symbols'}
        configuration 'linux'
            links {'pthread'}
